/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package calculator;

import java.awt.event.ActionEvent;
import java.util.Stack;
import java.util.Vector;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class Calculator extends javax.swing.JFrame {

    int action_code = 0;
    int input ;
    int result;
    int first_input;
    int second_input;
    
    
    public Calculator() {
     
        initComponents();
        
    }
    
    public void calculations()
    {
        if(action_code == 1) // Addition
        {
             second_input =  Integer.parseInt(display.getText().trim());
             result = first_input+second_input;
        }
       
        
        if(action_code ==2 ) // Mutiply
        {
             second_input =  Integer.parseInt(display.getText().trim());
             result = first_input*second_input;
        }
       
        if(action_code == 3) // Substraction
        {
            second_input =  Integer.parseInt(display.getText().trim());
             result = first_input-second_input;
        }
        
        if(action_code == 4) // Division
        {
             second_input =  Integer.parseInt(display.getText().trim());
             result = (first_input/second_input);
        }
        
        
        if(action_code == 5) // Modulus
        {
               second_input =  Integer.parseInt(display.getText().trim());
             result = first_input%second_input;
        }

        
        String r = Integer.toString(result);
        display.setText(r);
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar1 = new java.awt.MenuBar();
        menu1 = new java.awt.Menu();
        menu2 = new java.awt.Menu();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        display = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        i = new javax.swing.JButton();
        Clear = new javax.swing.JButton();
        modulus = new javax.swing.JButton();
        addition = new javax.swing.JButton();
        seven = new javax.swing.JButton();
        eight = new javax.swing.JButton();
        nine = new javax.swing.JButton();
        substraction = new javax.swing.JButton();
        four = new javax.swing.JButton();
        five = new javax.swing.JButton();
        six = new javax.swing.JButton();
        mutiply = new javax.swing.JButton();
        one = new javax.swing.JButton();
        two = new javax.swing.JButton();
        three = new javax.swing.JButton();
        division = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        zero = new javax.swing.JButton();
        execute = new javax.swing.JButton();

        menu1.setLabel("File");
        menuBar1.add(menu1);

        menu2.setLabel("Edit");
        menuBar1.add(menu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        display.setEditable(false);
        display.setBackground(new java.awt.Color(0, 0, 0));
        display.setColumns(20);
        display.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        display.setForeground(new java.awt.Color(255, 255, 255));
        display.setRows(5);
        display.setName("display"); // NOI18N
        jScrollPane2.setViewportView(display);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setLayout(new java.awt.GridLayout(4, 4, 0, 2));

        i.setBackground(new java.awt.Color(204, 255, 204));
        i.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        i.setText("ⓘ");
        i.setToolTipText("Information");
        i.setName("i"); // NOI18N
        i.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iActionPerformed(evt);
            }
        });
        jPanel2.add(i);

        Clear.setBackground(new java.awt.Color(255, 0, 0));
        Clear.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        Clear.setText("C");
        Clear.setName("Clear"); // NOI18N
        Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearActionPerformed(evt);
            }
        });
        jPanel2.add(Clear);

        modulus.setBackground(new java.awt.Color(153, 153, 0));
        modulus.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        modulus.setText("%");
        modulus.setName("modulus"); // NOI18N
        modulus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modulusActionPerformed(evt);
            }
        });
        jPanel2.add(modulus);

        addition.setBackground(new java.awt.Color(153, 153, 0));
        addition.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 18)); // NOI18N
        addition.setMnemonic('+');
        addition.setText("+");
        addition.setName("addition"); // NOI18N
        addition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                additionActionPerformed(evt);
            }
        });
        jPanel2.add(addition);

        seven.setBackground(new java.awt.Color(0, 153, 153));
        seven.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        seven.setMnemonic('7');
        seven.setText("7");
        seven.setName("seven"); // NOI18N
        seven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenActionPerformed(evt);
            }
        });
        jPanel2.add(seven);

        eight.setBackground(new java.awt.Color(0, 153, 153));
        eight.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        eight.setMnemonic('8');
        eight.setText("8");
        eight.setName("eight"); // NOI18N
        eight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightActionPerformed(evt);
            }
        });
        jPanel2.add(eight);

        nine.setBackground(new java.awt.Color(0, 153, 153));
        nine.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        nine.setMnemonic('9');
        nine.setText("9");
        nine.setName("nine"); // NOI18N
        nine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineActionPerformed(evt);
            }
        });
        jPanel2.add(nine);

        substraction.setBackground(new java.awt.Color(153, 153, 0));
        substraction.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 18)); // NOI18N
        substraction.setMnemonic('-');
        substraction.setText("-");
        substraction.setName("substraction"); // NOI18N
        substraction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                substractionActionPerformed(evt);
            }
        });
        jPanel2.add(substraction);

        four.setBackground(new java.awt.Color(0, 153, 153));
        four.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        four.setMnemonic('4');
        four.setText("4");
        four.setName("four"); // NOI18N
        four.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourActionPerformed(evt);
            }
        });
        jPanel2.add(four);

        five.setBackground(new java.awt.Color(0, 153, 153));
        five.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        five.setMnemonic('5');
        five.setText("5");
        five.setName("five"); // NOI18N
        five.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveActionPerformed(evt);
            }
        });
        jPanel2.add(five);

        six.setBackground(new java.awt.Color(0, 153, 153));
        six.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        six.setMnemonic('6');
        six.setText("6");
        six.setName("six"); // NOI18N
        six.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixActionPerformed(evt);
            }
        });
        jPanel2.add(six);

        mutiply.setBackground(new java.awt.Color(153, 153, 0));
        mutiply.setFont(new java.awt.Font("Gill Sans Ultra Bold", 0, 18)); // NOI18N
        mutiply.setText("x");
        mutiply.setName("mutiply"); // NOI18N
        mutiply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mutiplyActionPerformed(evt);
            }
        });
        jPanel2.add(mutiply);

        one.setBackground(new java.awt.Color(0, 153, 153));
        one.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        one.setMnemonic('1');
        one.setText("1");
        one.setName("one"); // NOI18N
        one.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneActionPerformed(evt);
            }
        });
        jPanel2.add(one);

        two.setBackground(new java.awt.Color(0, 153, 153));
        two.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        two.setMnemonic('2');
        two.setText("2");
        two.setName("two"); // NOI18N
        two.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoActionPerformed(evt);
            }
        });
        jPanel2.add(two);

        three.setBackground(new java.awt.Color(0, 153, 153));
        three.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        three.setMnemonic('3');
        three.setText("3");
        three.setName("three"); // NOI18N
        three.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeActionPerformed(evt);
            }
        });
        jPanel2.add(three);

        division.setBackground(new java.awt.Color(153, 153, 0));
        division.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 18)); // NOI18N
        division.setText("÷");
        division.setName("division"); // NOI18N
        division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divisionActionPerformed(evt);
            }
        });
        jPanel2.add(division);

        zero.setBackground(new java.awt.Color(0, 153, 153));
        zero.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        zero.setMnemonic('0');
        zero.setText("0");
        zero.setName("zero"); // NOI18N
        zero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroActionPerformed(evt);
            }
        });

        execute.setBackground(new java.awt.Color(102, 102, 0));
        execute.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 18)); // NOI18N
        execute.setText("=");
        execute.setName("execute"); // NOI18N
        execute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                executeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(zero, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(execute, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(zero, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
            .addComponent(execute, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearActionPerformed
        display.setText("");
        
    }//GEN-LAST:event_ClearActionPerformed

    private void iActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iActionPerformed
        JOptionPane.showMessageDialog(this,"This Calculator is developed by Ko Ko Lin Thant in June 2024. \n Github profile : https://github.com/kklt969 \n Email : kokolinthant785@gmail.com");
    }//GEN-LAST:event_iActionPerformed

    private void oneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneActionPerformed
        
        display.setText("");
        display.append("1");
    }//GEN-LAST:event_oneActionPerformed

    private void twoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoActionPerformed
       display.setText("");
        display.append("2");
    }//GEN-LAST:event_twoActionPerformed

    private void additionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_additionActionPerformed
       first_input = Integer.parseInt(display.getText().trim());
       display.setText("");
       action_code = 1;
       
    }//GEN-LAST:event_additionActionPerformed

    private void executeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_executeActionPerformed
       
        calculations();
        
        
    }//GEN-LAST:event_executeActionPerformed

    private void threeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeActionPerformed
        display.setText("");
        display.append("3");
    }//GEN-LAST:event_threeActionPerformed

    private void fourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourActionPerformed
        display.setText("");
        display.append("4");
    }//GEN-LAST:event_fourActionPerformed

    private void fiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveActionPerformed
        display.setText("");
        display.append("5");
    }//GEN-LAST:event_fiveActionPerformed

    private void sixActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixActionPerformed
       display.setText("");
        display.append("6");
    }//GEN-LAST:event_sixActionPerformed

    private void sevenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenActionPerformed
        display.setText("");
        display.append("7");
    }//GEN-LAST:event_sevenActionPerformed

    private void eightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightActionPerformed
        display.setText("");
        display.append("8");
    }//GEN-LAST:event_eightActionPerformed

    private void nineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineActionPerformed
        display.setText("");
        display.append("9");
    }//GEN-LAST:event_nineActionPerformed

    private void zeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroActionPerformed
        display.setText("");
        display.append("0");
    }//GEN-LAST:event_zeroActionPerformed

    private void mutiplyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mutiplyActionPerformed
        first_input = Integer.parseInt(display.getText().trim());
        display.setText("");
        action_code = 2;
        
    }//GEN-LAST:event_mutiplyActionPerformed

    private void substractionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_substractionActionPerformed
         first_input = Integer.parseInt(display.getText().trim());
        display.setText("");
        action_code = 3;
    }//GEN-LAST:event_substractionActionPerformed

    private void divisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divisionActionPerformed
         first_input = Integer.parseInt(display.getText().trim());
        display.setText("");
        action_code = 4;
    }//GEN-LAST:event_divisionActionPerformed

    private void modulusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modulusActionPerformed
         first_input = Integer.parseInt(display.getText().trim());
        display.setText("");
        action_code = 5;
    }//GEN-LAST:event_modulusActionPerformed

    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Clear;
    private javax.swing.JButton addition;
    private javax.swing.JTextArea display;
    private javax.swing.JButton division;
    private javax.swing.JButton eight;
    private javax.swing.JButton execute;
    private javax.swing.JButton five;
    private javax.swing.JButton four;
    private javax.swing.JButton i;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Menu menu1;
    private java.awt.Menu menu2;
    private java.awt.MenuBar menuBar1;
    private javax.swing.JButton modulus;
    private javax.swing.JButton mutiply;
    private javax.swing.JButton nine;
    private javax.swing.JButton one;
    private javax.swing.JButton seven;
    private javax.swing.JButton six;
    private javax.swing.JButton substraction;
    private javax.swing.JButton three;
    private javax.swing.JButton two;
    private javax.swing.JButton zero;
    // End of variables declaration//GEN-END:variables
}
